kind: pipeline
name: default
type: docker

steps:
  - name: publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_password
      repo: ghcr.io/sebasptsch/TDUWebsite
      registry: ghcr.io
      tags:
        - latest
